apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/thangamani-arun/gitops-lakehouse.git
    targetRevision: main
    path: infra/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
