apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-spark-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://kubeflow.github.io/spark-operator
    chart: spark-operator
    targetRevision: 2.5.2
    helm:
      releaseName: spark-operator
      values: |
        spark:
          jobNamespaces:
            - lakehouse-orchestration
        webhook:
          enable: true
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: lakehouse-orchestration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
