apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lakehouse-governance
resources:
  - mssql-source.yaml
  - iceberg-catalog.yaml
  - kafka-source.yaml
  - airflow-lineage.yaml
  - dashboard-source.yaml
