apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - airflow-pg.yaml
  - changelog-pg.yaml
  - polaris-pg.yaml
  - openmetadata-pg.yaml
  - ranger-pg.yaml
  - superset-pg.yaml
