apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: polaris-pg
  namespace: lakehouse-catalog
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  enableSuperuserAccess: false
  affinity:
    podAntiAffinityType: preferred
  bootstrap:
    initdb:
      database: polaris
      owner: polaris
      # secret omitted: CNPG auto-generates and manages polaris-pg-app
  storage:
    size: 10Gi
    storageClass: ceph-block-ec
  walStorage:
    size: 2Gi
    storageClass: ceph-block-ec
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  monitoring:
    enablePodMonitor: false
