apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-flink-jobs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/thangamani-arun/gitops-lakehouse.git
    targetRevision: main
    path: workloads/flink-jobs
  destination:
    server: https://kubernetes.default.svc
    namespace: lakehouse-streaming
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
